server:
    port: 8080
spring:
    main:
        web-application-type: reactive
    application:
        name: mall-gateway
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848 
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                -   id: mall-category
                    uri: http://localhost:8081
                    predicates:
                        -   Path=/api/category/**
